apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.19.1
  - awx-demo.yml
# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1

# Specify a custom namespace in which to install AWX
namespace: awx

---
spec:
  ...
  extra_volumes: |

    - name: local-host-playbooks
      persistentVolumeClaim:
        claimName: local-host-playbooks-claim

    - name: shared-volume
      persistentVolumeClaim:
        claimName: my-external-volume-claim

  init_container_extra_volume_mounts: |
    - name: local-host-playbooks
      mountPath: /var/lib/awx/projects

  init_container_extra_commands: |
    # set proper permissions (rwx) for the awx user
    chmod 775 /var/lib/awx/projects
    chgrp 1000 /var/lib/awx/projects
